version: '3.7'

services:
  postgres:
    build: ./exchange-rate-db
    ports:
      - "5432:5432"
    environment:
      - EXCHANGE_RATE_DB_DATABASE=exchangerate
      - EXCHANGE_RATE_DB_USER=exchangerate
      - EXCHANGE_RATE_DB_PASSWORD=exchangerate
    restart: always
    networks:
      backend:
        aliases:
          - pg11

  backend-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_USER=test
      - APP_PASSWORD=test
      - PG_SERVER=pg11
      - EXCHANGE_RATE_DB_DATABASE=exchangerate
      - EXCHANGE_RATE_DB_USER=exchangerate
      - EXCHANGE_RATE_DB_PASSWORD=exchangerate
      - EXCHANGE_RATE_EMAIL_USER=test@test.com
      - EXCHANGE_RATE_EMAIL_PASSWORD=test
    command: java -Duser.timezone=America/Managua -jar exchange-rate-service.jar
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
