export PG_SERVER=localhost
export EXCHANGE_RATE_DB_DATABASE=exchange-rate
export EXCHANGE_RATE_DB_USER=postgres
export EXCHANGE_RATE_DB_PASSWORD=postgres

echo "PG_SERVER=$PG_SERVER"
echo "EXCHANGE_RATE_DB_DATABASE=$EXCHANGE_RATE_DB_DATABASE"
echo "EXCHANGE_RATE_DB_USER=$EXCHANGE_RATE_DB_USER"
echo "EXCHANGE_RATE_DB_PASSWORD=**********"

